#pragma once

// This file is auto-generated by erl_dump_compile_definitions()

#ifndef EIGEN_USE_MKL_ALL
    #define EIGEN_USE_MKL_ALL
#endif

#ifndef ERL_USE_BOOST
    #define ERL_USE_BOOST
#endif

#ifndef ERL_USE_FMT
    #define ERL_USE_FMT
#endif

#ifndef ERL_USE_ABSL
    #define ERL_USE_ABSL
#endif

#ifndef YAML_CPP_VERSION_MAJOR
    #define YAML_CPP_VERSION_MAJOR 0
#endif

#ifndef YAML_CPP_VERSION_MINOR
    #define YAML_CPP_VERSION_MINOR 8
#endif

#ifndef YAML_CPP_VERSION_PATCH
    #define YAML_CPP_VERSION_PATCH 0
#endif

#ifndef ERL_USE_YAML
    #define ERL_USE_YAML
#endif

#ifndef ERL_USE_OPENCV
    #define ERL_USE_OPENCV
#endif

#ifndef ERL_USE_PLPLOT
    #define ERL_USE_PLPLOT
#endif

#ifndef ERL_USE_ABSL
    #define ERL_USE_ABSL
#endif

#ifndef ERL_USE_OPEN3D
    #define ERL_USE_OPEN3D
#endif

#ifndef ERL_BUILD_TEST
    #define ERL_BUILD_TEST
#endif

#ifndef EIGEN_FUNCTORS_PLUGIN
    #define EIGEN_FUNCTORS_PLUGIN "grid_map_core/eigen_plugins/FunctorsPlugin.hpp"
#endif

#ifndef EIGEN_DENSEBASE_PLUGIN
    #define EIGEN_DENSEBASE_PLUGIN "grid_map_core/eigen_plugins/DenseBasePlugin.hpp"
#endif

