local_bhm:
    bhm:
        diagonal_sigma: true
        min_distance: 0.3
        max_distance: 3.5
        free_points_per_meter: 3
        free_sampling_margin: 0.001
        init_mu: 0.0
        init_sigma: 10000
        num_em_iterations: 2
        sparse_zero_threshold: 1.0e-3
        use_sparse: true
    kernel_type: erl::covariance::RadialBiasFunction<float, 3>
    kernel_setting_type: erl::covariance::Covariance<float>::Setting
    kernel:
        x_dim: 3
        scale: 0.025
        scale_mix: 1
        weights: [ ]
    max_dataset_size: 2000
    hit_buffer_size: 0
    surface_resolution: 0.1
ray_selector:
    azimuth_min: -0.55
    azimuth_max: 0.55
    elevation_min: -0.43
    elevation_max: 0.43
    num_azimuth_angles: 640
    num_elevation_angles: 480
tree:
    resolution: 0.1  # 0.15 # 0.1
    tree_depth: 16
    log_odd_min: -10
    log_odd_max: 10
    log_odd_hit: 0.7
    log_odd_miss: -0.5
    log_odd_occ_threshold: 0
    use_change_detection: false
    use_aabb_limit: false
    aabb:
        center: [ 0, 0, 0 ]
        half_sizes: [ 0, 0, 0 ]
hinged_grid_size: 5
surface_max_abs_logodd: 2
surface_bad_abs_logodd: 100
surface_step_size: 0.001
faster_prediction: true
max_adjust_tries: 2
var_scale: 0.01
var_max: 1.5
scaling: 1.0
bhm_depth: 15
bhm_overlap: 0.08  # 0.15 # 0.12
update_with_cuda: false
cuda_device_id: 0
update_batch_size: 128
bhm_test_margin: 0.07 # 0.12 # 0.1
test_knn: 1
test_batch_size: 1000
build_bhm_on_hit: true
