__base__: ../common/bayesian_hilbert_surf_mapping_float.yaml
local_bhm:
    bhm:
        diagonal_sigma: true
        min_distance: 0.15
        max_distance: 1.5
        sampling_area_scale: 2.5
        free_points_per_meter: 3
        free_sampling_margin: 0.001
        init_mu: 5.0
        init_sigma: 10000
        num_em_iterations: 1
        sparse_zero_threshold: 0.003
        use_sparse: true
    kernel_type: erl::covariance::RadialBiasFunction<float, 3>
    kernel_setting_type: erl::covariance::Covariance<float>::Setting
    kernel:
        x_dim: 3
        scale: 0.012
        scale_mix: 1
        weights: []
    min_dataset_size: 30
    min_dataset_hit_size: 15
    max_dataset_size: 150
    hit_point_buffer_size: 128
    ray_buffer_size: 1024
    surface_grid_size: 10
    surface_log_odds: 5.0
    surface_log_odds_lr: 0.8
    surface_log_odds_init_count: 1
    surface_log_odds_min: -5.0
    surface_log_odds_max: 20.0
    faster_prediction: true
ray_selector:
    azimuth_min: -0.79
    azimuth_max: 0.79
    elevation_min: -0.52
    elevation_max: 0.52
    num_azimuth_angles: 848
    num_elevation_angles: 480
    transform: # transform from optical frame to camera frame
        - [ 0, 0, 1, 0 ]
        - [ -1, 0, 0, 0 ]
        - [ 0, -1, 0, 0 ]
tree:
    resolution: 0.05
    tree_depth: 10
    log_odd_min: -10
    log_odd_max: 100
    log_odd_hit: 0.9
    log_odd_miss: -0.01
    log_odd_occ_threshold: 0
    use_change_detection: false
    use_aabb_limit: false
    aabb:
        center: [0, 0, 0]
        half_sizes: [0, 0, 0]
update_tree:
    with_count: false
    parallel: true
    lazy_eval: true
    discrete: true
update_map:
    method: 2
    surface_max_abs_logodd: 2
    surface_bad_abs_logodd: 200
    surface_step_size: 0.001
    auto_surface_log_odds: true
    max_num_bhm: 1500
    max_num_voxels: 8000
    var_scale: 0.01
    var_max: 1.5
bhm_depth: 9
hinged_grid_size: 7
build_bhm_on_hit: true
bhm_test_margin: 0.0225
unknown_log_odds: -100.0 # unknown space log-odds
sync_method: "mean" # copy, mean, or bayesian
