surface_mapping_setting_type: erl::gp_sdf::BayesianHilbertSurfaceMapping<float, 2>::Setting
surface_mapping_setting_file: config/template/bayesian_hilbert_mapping_2d_float.yaml
surface_mapping_type: erl::gp_sdf::BayesianHilbertSurfaceMapping<float, 2>
sdf_mapping_setting_file: erl_gp_sdf/config/template/sdf_mapping_2d_float.yaml
odom:
    enabled: false
    topic: /jackal_velocity_controller/odom
    msg_type: transform_stamped # "odometry" or "transform_stamped"
    queue_size: 200
world_frame: map
sensor_frame: front_laser
scan:
    topic: /front/scan
    type: laser # "laser", "point_cloud", or "depth"
    frame_type: erl::geometry::LidarFrame2D<float>
    frame_setting_file: config/sensors/lidar_frame_2d.yaml
    stride: 1
    convert_to_points: true
    in_local_frame: false # converted to points in the world frame
    depth_scale: 0.001
paint_surface:
    color_from_scan: false
    topic: ""
    topic_type: image # "pcd" or "image"
    overwrite: true
publish_tree:
    enabled: false
    binary: true
    frequency: 5.0
    topic: surface_mapping_tree
publish_surface_points:
    enabled: false
    frequency: 5.0
    topic: surface_points
publish_mesh:
    enabled: false
    frequency: 1.0
    topic: mesh
publish_occupancy_grid:
    enabled: false
    frequency: 5.0
    topic: occupancy_grid
update_time_topic: update_time
query_time_topic: query_time
sdf_query_service: sdf_query
occ_query_service: occ_query
save_map_service: save_map
load_map_service: load_map
save_mesh_service: save_mesh
